import { Credential } from '../../data-objects/credential';
import { test } from '../../fixtures/beforeAndAfterTest';

test('TC 14A: Verify users can login successfully', async ({ homePageClean, loginPageClean }) => {
  await test.step('Step #1: Open the site', async () => {
    await homePageClean.navigateToTestSite();
  });

  await test.step('Step #2: Login the site', async () => {
    await homePageClean.clickLoginLink();
    await loginPageClean.login();
  });

  await test.step('Step #3: Verify user is logged in', async () => {
    await homePageClean.verifyLoginLinkHidden();
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});

test('TC 14B: Verify users can logout successfully', async ({ homePageClean, loginPageClean, myAccountPageClean }) => {
  await test.step('Step #1: Open the site', async () => {
    await homePageClean.navigateToTestSite();
  });

  await test.step('Step #2: Login the site', async () => {
    await homePageClean.clickLoginLink();
    await loginPageClean.login();
  });

  await test.step('Step #3: Go to the Manage my account page', async () => {
    await homePageClean.clickMyAccountLink();
  });

  await test.step('Step #4: Logout and verify user is logged out', async () => {
    await myAccountPageClean.logout();
    await homePageClean.verifyLoginLinkVisible();
    await myAccountPageClean.verifyLogoutLinkIsHidden();
    await homePageClean.clickLoginLink();
    await loginPageClean.verifyLoginFormIsVisible();
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});

test('TC 14C: Verify session persists after refresh', async ({ page, homePageClean, loginPageClean, myAccountPageClean }) => {
  await test.step('Step #1: Open the site', async () => {
    await homePageClean.navigateToTestSite();
  });

  await test.step('Step #2: Login the site', async () => {
    await homePageClean.clickLoginLink();
    await loginPageClean.login();
  });

  await test.step('Step #3: Refresh the page', async () => {
    await page.reload();
    await page.waitForLoadState('networkidle');
  });

  await test.step('Step #4: Verify user is still logged in', async () => {
    await homePageClean.verifyLoginLinkHidden();
    await homePageClean.clickMyAccountLink();
    await myAccountPageClean.verifyLogoutLinkIsVisible();
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});

test('TC 14D: Verify invalid password shows error and stays on login', async ({ homePageClean, loginPageClean }) => {
  await test.step('Step #1: Open the site', async () => {
    await homePageClean.navigateToTestSite();
  });

  await test.step('Step #2: Go to login page', async () => {
    await homePageClean.clickLoginLink();
  });

  await test.step('Step #3: Submit invalid password', async () => {
    const _cred = new Credential({ username: 'dudu1236@sharklasers.com', password: 'wrongpass' });
    await loginPageClean.login(_cred, false);
  });

  await test.step('Step #4: Verify error is shown and user stays on login', async () => {
    await loginPageClean.verifyErrorMessageContains('password you entered');
    await loginPageClean.verifyLoginFormIsVisible();
    await loginPageClean.verifyLoginLinkVisible();
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});

test('TC 14E: Verify unknown username shows error', async ({ homePageClean, loginPageClean }) => {
  await test.step('Step #1: Open the site', async () => {
    await homePageClean.navigateToTestSite();
  });

  await test.step('Step #2: Go to login page', async () => {
    await homePageClean.clickLoginLink();
  });

  await test.step('Step #3: Submit unknown username', async () => {
    const _cred = new Credential({ username: 'unknown_user@example.com', password: 'AnyPass123' });
    await loginPageClean.login(_cred, false);
  });

  await test.step('Step #4: Verify error is shown and user stays on login', async () => {
    await loginPageClean.verifyErrorMessageContains('Unknown email address');
    await loginPageClean.verifyLoginFormIsVisible();
    await loginPageClean.verifyLoginLinkVisible();
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});

test('TC 14F: Verify empty username shows required validation', async ({ homePageClean, loginPageClean }) => {
  await test.step('Step #1: Open the site', async () => {
    await homePageClean.navigateToTestSite();
  });

  await test.step('Step #2: Go to login page', async () => {
    await homePageClean.clickLoginLink();
  });

  await test.step('Step #3: Submit empty username', async () => {
    const _cred = new Credential({ username: '', password: 'AnyPass123' });
    await loginPageClean.login(_cred, false);
  });

  await test.step('Step #4: Verify error is shown and user stays on login', async () => {
    await loginPageClean.verifyErrorMessageContains('Username is required');
    await loginPageClean.verifyLoginFormIsVisible();
    await loginPageClean.verifyLoginLinkVisible();
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});

test('TC 14G: Verify empty password shows required validation', async ({ homePageClean, loginPageClean }) => {
  await test.step('Step #1: Open the site', async () => {
    await homePageClean.navigateToTestSite();
  });

  await test.step('Step #2: Go to login page', async () => {
    await homePageClean.clickLoginLink();
  });

  await test.step('Step #3: Submit empty password', async () => {
    const _cred = new Credential({ username: 'dudu1236@sharklasers.com', password: '' });
    await loginPageClean.login(_cred, false);
  });

  await test.step('Step #4: Verify error is shown and user stays on login', async () => {
    await loginPageClean.verifyErrorMessageContains('password field is empty');
    await loginPageClean.verifyLoginFormIsVisible();
    await loginPageClean.verifyLoginLinkVisible();
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});

test('TC 14H: Verify both fields empty shows validation', async ({ homePageClean, loginPageClean }) => {
  await test.step('Step #1: Open the site', async () => {
    await homePageClean.navigateToTestSite();
  });

  await test.step('Step #2: Go to login page', async () => {
    await homePageClean.clickLoginLink();
  });

  await test.step('Step #3: Submit empty username and password', async () => {
    const _cred = new Credential({ username: '', password: '' });
    await loginPageClean.login(_cred, false);
  });

  await test.step('Step #4: Verify error is shown and user stays on login', async () => {
    await loginPageClean.verifyErrorMessageContains('Username is required');
    await loginPageClean.verifyLoginFormIsVisible();
    await loginPageClean.verifyLoginLinkVisible();
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});

test('TC 14I: Verify password is masked', async ({ homePageClean, loginPageClean }) => {
  await test.step('Step #1: Open the site', async () => {
    await homePageClean.navigateToTestSite();
  });

  await test.step('Step #2: Go to login page', async () => {
    await homePageClean.clickLoginLink();
  });

  await test.step('Step #3: Verify password input type is password', async () => {
    await loginPageClean.verifyPasswordIsMasked();
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});

test('TC 14J: Verify error message clears after successful login', async ({ homePageClean, loginPageClean }) => {
  await test.step('Step #1: Open the site', async () => {
    await homePageClean.navigateToTestSite();
  });

  await test.step('Step #2: Go to login page', async () => {
    await homePageClean.clickLoginLink();
  });

  await test.step('Step #3: Trigger an error message', async () => {
    const _cred = new Credential({ username: '', password: '' });
    await loginPageClean.login(_cred, false);
    await loginPageClean.verifyErrorMessageContains('Username is required');
  });

  await test.step('Step #4: Login successfully', async () => {
    await loginPageClean.login();
  });

  await test.step('Step #5: Verify error message is cleared', async () => {
    await loginPageClean.verifyErrorMessageHidden();
    await homePageClean.verifyLoginLinkHidden();
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});
