import { test } from '../../fixtures/beforeAndAfterTest';
import { MenuTab } from '../../data-objects/dataEnums';

test('TC 13: Verify product thumbnail action icons on Shop page', async ({ homePage, productPage }) => {
  await test.step('Step #1: Open the site', async () => {
    await homePage.navigateToTestSite();
  });

  await test.step('Step #2: Go to the Shop page', async () => {
    await homePage.clickMenuTab(MenuTab.SHOP);
  });

  await test.step('Step #3: Verify that all other products in the page have all 3 thumbnails each', async () => {
    await productPage.verifyProductsHaveThreeActionThumbnailsAndCorrectPurposes();
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});
