import { test } from '../../fixtures/beforeAndAfterTest';
import { TestDataUtils } from '../../utils/testDataLoader';

const wholeDataSet: Record<string, Record<string, any>[]> = TestDataUtils.loadFullDataSet(__filename);

const testCaseTitleTC15A = 'TC 15A: Verify user can search for product successfully';
for (const testData of wholeDataSet[testCaseTitleTC15A]) {
  test(`${testCaseTitleTC15A} - ${testData.setNo}`, async ({ homePage, productPage }) => {
    await test.step('Step #1: Open the site', async () => {
      await homePage.navigateToTestSite();
    });

    await test.step('Step #2: Search for a product', async () => {
      await productPage.searchProduct(testData.query, testData.submitType);
    });

    await test.step('Step #3: Verify search result behavior', async () => {
      if (testData.expectedPage === 'details') {
        await productPage.verifyProductDetailsPageFor(testData.expectedProduct);
      } else {
        await productPage.verifySearchResultsPageFor(testData.query);
        await productPage.verifySearchResultsNotEmpty();
        if (testData.expectedProducts) {
          await productPage.verifySearchResultsContain(testData.expectedProducts);
        }
      }
    });

    // THIS TEST IS GENERATED BY AGENT SKILLS!
  });
}

test("TC 15B: Verify search shows no results if there is no product with matching-name", async ({ homePage, productPage }) => {
  const query: string = 'water jet motor';
  await test.step('Step #1: Open the site', async () => {
    await homePage.navigateToTestSite();
  });

  await test.step('Step #2: Search for a product', async () => {
    await productPage.searchProduct(query);
  });

  await test.step('Step #3: Verify no results are shown', async () => {
    await productPage.verifySearchResultsPageFor(query);
    await productPage.verifyNoProductsFound();
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});


test("TC 15C: Verify search handles special characters", async ({ homePage, productPage }) => {
  const query: string = "@#$%^&*";
  await test.step('Step #1: Open the site', async () => {
    await homePage.navigateToTestSite();
  });

  await test.step('Step #2: Search for a product', async () => {
    await productPage.searchProduct(query);
  });

  await test.step('Step #3: Verify no results are shown', async () => {
    await productPage.verifySearchResultsPageFor(query);
    await productPage.verifyNoProductsFound();
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});

test("TC15D: Verify whitespace search returns product results", async ({ homePage, productPage }) => {
  const query: string = " ";
  const expectedProducts: string[] = ['DJI Phantom 4 Camera Drone', 'DJI Mavic Pro Camera Drone',
    'iPad Air 2', 'Robotic Arm Edge', 'Velleman Vertex K 8400',
    'RoboXplorer Multi Terrain Robotic', 'AirPods']

  await test.step('Step #1: Open the site', async () => {
    await homePage.navigateToTestSite();
  });

  await test.step('Step #2: Search for a product', async () => {
    await productPage.searchProduct(query);
  });

  await test.step('Step #3: Verify results are shown for whitespace search', async () => {
    await productPage.verifySearchResultsPageFor(query);
    await productPage.verifySearchResultsNotEmpty();
    await productPage.verifySearchResultsContain(expectedProducts);
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});

test("TC 15E: Verify the search function return the same list of products when logged out vs logged in", async ({ homePageClean, productPageClean, homePage, productPage }) => {
  const query: string = "Robo";
  let loggedOutTitles: string[] = [];
  await test.step('Step #1: Open the site (logged out)', async () => {
    await homePageClean.navigateToTestSite();
  });

  await test.step('Step #2: Search for a product (logged out)', async () => {
    await productPageClean.searchProduct(query);
  });

  await test.step('Step #3: Verify search results are shown (logged out)', async () => {
    await productPageClean.verifySearchResultsPageFor(query);
    await productPageClean.verifySearchResultsNotEmpty();
    loggedOutTitles = await productPageClean.getSearchResultsTitles();
  });

  await test.step('Step #4: Open the site (logged in)', async () => {
    await homePage.navigateToTestSite();
  });

  await test.step('Step #5: Search for a product (logged in)', async () => {
    await productPage.searchProduct(query);
  });

  await test.step('Step #6: Verify search results are shown (logged in)', async () => {
    await productPage.verifySearchResultsPageFor(query);
    await productPage.verifySearchResultsNotEmpty();
    await productPage.verifySearchResultsTitlesEqual(loggedOutTitles);
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});
