import { test } from '../../fixtures/beforeAndAfterTest';
import { MenuTab } from '../../data-objects/dataEnums';

const testCaseTitleTC12 = 'TC 12: Verify the back-to-top button visibility and behavior';
const menuTabsToVerify: { tab: MenuTab; name: string }[] = [
  { tab: MenuTab.HOME, name: 'Home' },
  { tab: MenuTab.ABOUT_US, name: 'About Us' },
  { tab: MenuTab.SHOP, name: 'Shop' },
  { tab: MenuTab.OFFERS, name: 'Offers' },
  { tab: MenuTab.BLOG, name: 'Blog' },
  { tab: MenuTab.CONTACT_US, name: 'Contact Us' },
];

for (const { tab, name } of menuTabsToVerify) {
  test(`${testCaseTitleTC12} - ${name} page`, async ({ homePage, productPage }) => {
    await test.step('Step #1: Open the site', async () => {
      await homePage.navigateToTestSite();
    });

    await test.step(`Step #2: Go to the ${name} page`, async () => {
      await homePage.clickMenuTab(tab);
    });

    await test.step('Step #3: Verify that the Back-to-top button is not displayed by default', async () => {
      await productPage.verifyBackToTopBtnIsHidden();
    });

    await test.step('Step #4: Scroll down the page a bit', async () => {
      await productPage.scrollByAmount(30);
    });

    await test.step('Step #5: Verify that the Back-to-top button is now DISPLAYED in the bottom-right corner', async () => {
      await productPage.verifyBackToTopBtnInBottomRight();
    });

    await test.step('Step #6: Click on the back-to-top button', async () => {
      await productPage.clickBackToTopButton();
    });

    await test.step('Step #7: Verify page is scrolled back to the top and the Back-to-top button is not displayed anymore', async () => {
      await productPage.verifyBackToTopBtnIsHidden();
      await productPage.verifyIsAtTopOfThePage();
    });

    await test.step('Step #8: Scroll down the page by a viewport height', async () => {
      await productPage.scrollDownByViewportHeight();
    });

    await test.step('Step #9: Verify that the Back-to-top button is now DISPLAYED in the bottom-right corner', async () => {
      await productPage.verifyBackToTopBtnInBottomRight();
    });

    await test.step('Step #10: Click on the back-to-top button', async () => {
      await productPage.clickBackToTopButton();
    });

    await test.step('Step #11: Verify page is scrolled back to the top and the Back-to-top button is not displayed anymore', async () => {
      await productPage.verifyBackToTopBtnIsHidden();
      await productPage.verifyIsAtTopOfThePage();
    });

    await test.step('Step #12: Scroll to the bottom of the page', async () => {
      await productPage.scrollToBottom();
    });

    await test.step('Step #13: Verify that the Back-to-top button is now DISPLAYED in the bottom-right corner', async () => {
      await productPage.verifyBackToTopBtnInBottomRight();
    });

    await test.step('Step #14: Click on the back-to-top button', async () => {
      await productPage.clickBackToTopButton();
    });

    await test.step('Step #15: Verify page is scrolled back to the top and the Back-to-top button is not displayed anymore', async () => {
      await productPage.verifyBackToTopBtnIsHidden();
      await productPage.verifyIsAtTopOfThePage();
    });

    // THIS TEST IS GENERATED BY AGENT SKILLS!
  });
}
