import { test, expect } from '../../fixtures/beforeAndAfterTest';

test('TC 11: Verify orders id are sorted in descending order across pages', async ({ homePage, myAccountPage }) => {
  const allOrderIds: number[] = [];

  await test.step('Step #1: Open the site', async () => {
    await homePage.navigateToTestSite();
  });

  await test.step('Step #2: Go to the Manage my account page', async () => {
    await homePage.clickMyAccountLink();
  });

  await test.step('Step #3: Go to the My orders page', async () => {
    await myAccountPage.clickRecentOrdersButton();
  });

  await test.step('Step #4: Validate that there is a table of orders displayed', async () => {
    const currentOrderIds = await myAccountPage.getCurrentOrderIdsList();
    expect(currentOrderIds.length).toBeGreaterThan(0);
  });

  await test.step('Step #5: Memoize the ids of the current orders in the table', async () => {
    const currentOrderIds = await myAccountPage.getCurrentOrderIdsList();
    allOrderIds.push(...currentOrderIds);
  });

  await test.step('Step #6: Go to the next page of the orders record', async () => {
    await myAccountPage.goToNextOrderRecordPage();
  });

  await test.step('Step #7: Memoize the ids of the current orders in the table and append them into the list', async () => {
    const currentOrderIds = await myAccountPage.getCurrentOrderIdsList();
    allOrderIds.push(...currentOrderIds);
  });

  await test.step('Step #8: Go to the another next page of the orders record', async () => {
    await myAccountPage.goToNextOrderRecordPage();
  });

  await test.step('Step #9: Memoize the ids of the current orders in the table and append them into the list', async () => {
    const currentOrderIds = await myAccountPage.getCurrentOrderIdsList();
    allOrderIds.push(...currentOrderIds);
  });

  await test.step('Step #10: Validate that the ids in the list are in descending order', async () => {
    const sortedDesc = [...allOrderIds].sort((a, b) => b - a);
    expect(allOrderIds).toStrictEqual(sortedDesc);
  });

  // THIS TEST IS GENERATED BY AGENT SKILLS!
});
