name: Playwright CI/CD Tests
on:
  push:
    branches: [main-unused, develop-unused]
  pull_request:
    branches: [main-unused, develop-unused]
env:
  BASE_URL: ${{ vars.BASE_URL || 'undefined base_url' }}
  VALID_USERNAME_1: ${{ secrets.VALID_USERNAME_1 || 'undefined_username_1' }}
  VALID_PASSWORD_1: ${{ secrets.VALID_PASSWORD_1 || 'undefined_password_1' }}
  VALID_USERNAME_2: ${{ secrets.VALID_USERNAME_2 || 'undefined_username_2' }}
  VALID_PASSWORD_2: ${{ secrets.VALID_PASSWORD_2 || 'undefined_password_2' }}
  CI: true
  USE_TEST_SHARDING: true
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  playwright-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment: qa
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --project=chromium

      - name: Upload blob reports to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-shard-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1

      - name: Upload Allure results to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-shard-${{ matrix.shardIndex }}
          path: allure-results/
          retention-days: 1

  merge-reports:
    if: ${{ !cancelled() }}
    needs: [playwright-test]

    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v5
        with:
          path: all-blob-reports
          pattern: blob-report-shard-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report-attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-shard-*
          path: merged-allure-results/
          merge-multiple: true

      - name: Generate Allure Report
        run: npx allure generate merged-allure-results -o allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-attempt-${{ github.run_attempt }}
          path: allure-report
          retention-days: 14
